name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NorekPlanMachining
          path: app/build/outputs/apk/debug/app-debug.apk
